// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: user.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ============ 基础响应结构 ============
type BaseResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Code          int64                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseResp) Reset() {
	*x = BaseResp{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResp) ProtoMessage() {}

func (x *BaseResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResp.ProtoReflect.Descriptor instead.
func (*BaseResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *BaseResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *BaseResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

// ============ Order 相关消息 ============
type OrderInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	Num           int64                  `protobuf:"varint,4,opt,name=num,proto3" json:"num,omitempty"`
	OrderSn       int64                  `protobuf:"varint,5,opt,name=orderSn,proto3" json:"orderSn,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,7,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderInfo) Reset() {
	*x = OrderInfo{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderInfo) ProtoMessage() {}

func (x *OrderInfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderInfo.ProtoReflect.Descriptor instead.
func (*OrderInfo) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *OrderInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OrderInfo) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OrderInfo) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *OrderInfo) GetOrderSn() int64 {
	if x != nil {
		return x.OrderSn
	}
	return 0
}

func (x *OrderInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *OrderInfo) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// ============ Create (创建) ============
type OrderCreateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Price         float64                `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	Num           int64                  `protobuf:"varint,3,opt,name=num,proto3" json:"num,omitempty"`
	OrderSn       int64                  `protobuf:"varint,4,opt,name=orderSn,proto3" json:"orderSn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderCreateReq) Reset() {
	*x = OrderCreateReq{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCreateReq) ProtoMessage() {}

func (x *OrderCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCreateReq.ProtoReflect.Descriptor instead.
func (*OrderCreateReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *OrderCreateReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OrderCreateReq) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OrderCreateReq) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *OrderCreateReq) GetOrderSn() int64 {
	if x != nil {
		return x.OrderSn
	}
	return 0
}

type OrderCreateResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Code          int64                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Data          *OrderInfo             `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderCreateResp) Reset() {
	*x = OrderCreateResp{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCreateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCreateResp) ProtoMessage() {}

func (x *OrderCreateResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCreateResp.ProtoReflect.Descriptor instead.
func (*OrderCreateResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *OrderCreateResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *OrderCreateResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *OrderCreateResp) GetData() *OrderInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

// ============ Read/List (查询) ============
type OrderGetReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderGetReq) Reset() {
	*x = OrderGetReq{}
	mi := &file_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderGetReq) ProtoMessage() {}

func (x *OrderGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderGetReq.ProtoReflect.Descriptor instead.
func (*OrderGetReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{4}
}

func (x *OrderGetReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type OrderGetResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Code          int64                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Data          *OrderInfo             `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderGetResp) Reset() {
	*x = OrderGetResp{}
	mi := &file_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderGetResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderGetResp) ProtoMessage() {}

func (x *OrderGetResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderGetResp.ProtoReflect.Descriptor instead.
func (*OrderGetResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{5}
}

func (x *OrderGetResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *OrderGetResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *OrderGetResp) GetData() *OrderInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

// 三条件组合查询请求
type OrderListReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 分页参数
	Page     int64 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize int64 `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	// 条件1：名称模糊查询
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// 条件2：价格区间
	MinPrice float64 `protobuf:"fixed64,4,opt,name=minPrice,proto3" json:"minPrice,omitempty"` // 最低价格
	MaxPrice float64 `protobuf:"fixed64,5,opt,name=maxPrice,proto3" json:"maxPrice,omitempty"` // 最高价格
	// 条件3：创建时间范围
	StartTime     string `protobuf:"bytes,6,opt,name=startTime,proto3" json:"startTime,omitempty"` // 开始时间 (格式: 2024-01-01 00:00:00)
	EndTime       string `protobuf:"bytes,7,opt,name=endTime,proto3" json:"endTime,omitempty"`     // 结束时间 (格式: 2024-12-31 23:59:59)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderListReq) Reset() {
	*x = OrderListReq{}
	mi := &file_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderListReq) ProtoMessage() {}

func (x *OrderListReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderListReq.ProtoReflect.Descriptor instead.
func (*OrderListReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{6}
}

func (x *OrderListReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *OrderListReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *OrderListReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OrderListReq) GetMinPrice() float64 {
	if x != nil {
		return x.MinPrice
	}
	return 0
}

func (x *OrderListReq) GetMaxPrice() float64 {
	if x != nil {
		return x.MaxPrice
	}
	return 0
}

func (x *OrderListReq) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *OrderListReq) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

type OrderListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Code          int64                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Data          []*OrderInfo           `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Total         int64                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderListResp) Reset() {
	*x = OrderListResp{}
	mi := &file_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderListResp) ProtoMessage() {}

func (x *OrderListResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderListResp.ProtoReflect.Descriptor instead.
func (*OrderListResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{7}
}

func (x *OrderListResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *OrderListResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *OrderListResp) GetData() []*OrderInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *OrderListResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// ============ Update (更新) ============
type OrderUpdateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	Num           int64                  `protobuf:"varint,4,opt,name=num,proto3" json:"num,omitempty"`
	OrderSn       int64                  `protobuf:"varint,5,opt,name=orderSn,proto3" json:"orderSn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderUpdateReq) Reset() {
	*x = OrderUpdateReq{}
	mi := &file_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderUpdateReq) ProtoMessage() {}

func (x *OrderUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderUpdateReq.ProtoReflect.Descriptor instead.
func (*OrderUpdateReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{8}
}

func (x *OrderUpdateReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderUpdateReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OrderUpdateReq) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OrderUpdateReq) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *OrderUpdateReq) GetOrderSn() int64 {
	if x != nil {
		return x.OrderSn
	}
	return 0
}

type OrderUpdateResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Code          int64                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Data          *OrderInfo             `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderUpdateResp) Reset() {
	*x = OrderUpdateResp{}
	mi := &file_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderUpdateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderUpdateResp) ProtoMessage() {}

func (x *OrderUpdateResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderUpdateResp.ProtoReflect.Descriptor instead.
func (*OrderUpdateResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{9}
}

func (x *OrderUpdateResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *OrderUpdateResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *OrderUpdateResp) GetData() *OrderInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

// ============ Delete (删除) ============
type OrderDeleteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderDeleteReq) Reset() {
	*x = OrderDeleteReq{}
	mi := &file_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderDeleteReq) ProtoMessage() {}

func (x *OrderDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderDeleteReq.ProtoReflect.Descriptor instead.
func (*OrderDeleteReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{10}
}

func (x *OrderDeleteReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type OrderDeleteResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Code          int64                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderDeleteResp) Reset() {
	*x = OrderDeleteResp{}
	mi := &file_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderDeleteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderDeleteResp) ProtoMessage() {}

func (x *OrderDeleteResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderDeleteResp.ProtoReflect.Descriptor instead.
func (*OrderDeleteResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{11}
}

func (x *OrderDeleteResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *OrderDeleteResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\x05proto\"0\n" +
	"\bBaseResp\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x03R\x04code\"\xad\x01\n" +
	"\tOrderInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x12\x10\n" +
	"\x03num\x18\x04 \x01(\x03R\x03num\x12\x18\n" +
	"\aorderSn\x18\x05 \x01(\x03R\aorderSn\x12\x1c\n" +
	"\tcreatedAt\x18\x06 \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\a \x01(\tR\tupdatedAt\"f\n" +
	"\x0eOrderCreateReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x01R\x05price\x12\x10\n" +
	"\x03num\x18\x03 \x01(\x03R\x03num\x12\x18\n" +
	"\aorderSn\x18\x04 \x01(\x03R\aorderSn\"]\n" +
	"\x0fOrderCreateResp\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x03R\x04code\x12$\n" +
	"\x04data\x18\x03 \x01(\v2\x10.proto.OrderInfoR\x04data\"\x1d\n" +
	"\vOrderGetReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"Z\n" +
	"\fOrderGetResp\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x03R\x04code\x12$\n" +
	"\x04data\x18\x03 \x01(\v2\x10.proto.OrderInfoR\x04data\"\xc2\x01\n" +
	"\fOrderListReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x03R\bpageSize\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1a\n" +
	"\bminPrice\x18\x04 \x01(\x01R\bminPrice\x12\x1a\n" +
	"\bmaxPrice\x18\x05 \x01(\x01R\bmaxPrice\x12\x1c\n" +
	"\tstartTime\x18\x06 \x01(\tR\tstartTime\x12\x18\n" +
	"\aendTime\x18\a \x01(\tR\aendTime\"q\n" +
	"\rOrderListResp\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x03R\x04code\x12$\n" +
	"\x04data\x18\x03 \x03(\v2\x10.proto.OrderInfoR\x04data\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x03R\x05total\"v\n" +
	"\x0eOrderUpdateReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x12\x10\n" +
	"\x03num\x18\x04 \x01(\x03R\x03num\x12\x18\n" +
	"\aorderSn\x18\x05 \x01(\x03R\aorderSn\"]\n" +
	"\x0fOrderUpdateResp\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x03R\x04code\x12$\n" +
	"\x04data\x18\x03 \x01(\v2\x10.proto.OrderInfoR\x04data\" \n" +
	"\x0eOrderDeleteReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"7\n" +
	"\x0fOrderDeleteResp\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x03R\x04code2\xb5\x02\n" +
	"\fOrderService\x12<\n" +
	"\vOrderCreate\x12\x15.proto.OrderCreateReq\x1a\x16.proto.OrderCreateResp\x123\n" +
	"\bOrderGet\x12\x12.proto.OrderGetReq\x1a\x13.proto.OrderGetResp\x126\n" +
	"\tOrderList\x12\x13.proto.OrderListReq\x1a\x14.proto.OrderListResp\x12<\n" +
	"\vOrderUpdate\x12\x15.proto.OrderUpdateReq\x1a\x16.proto.OrderUpdateResp\x12<\n" +
	"\vOrderDelete\x12\x15.proto.OrderDeleteReq\x1a\x16.proto.OrderDeleteRespB\x04Z\x02./b\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_user_proto_goTypes = []any{
	(*BaseResp)(nil),        // 0: proto.BaseResp
	(*OrderInfo)(nil),       // 1: proto.OrderInfo
	(*OrderCreateReq)(nil),  // 2: proto.OrderCreateReq
	(*OrderCreateResp)(nil), // 3: proto.OrderCreateResp
	(*OrderGetReq)(nil),     // 4: proto.OrderGetReq
	(*OrderGetResp)(nil),    // 5: proto.OrderGetResp
	(*OrderListReq)(nil),    // 6: proto.OrderListReq
	(*OrderListResp)(nil),   // 7: proto.OrderListResp
	(*OrderUpdateReq)(nil),  // 8: proto.OrderUpdateReq
	(*OrderUpdateResp)(nil), // 9: proto.OrderUpdateResp
	(*OrderDeleteReq)(nil),  // 10: proto.OrderDeleteReq
	(*OrderDeleteResp)(nil), // 11: proto.OrderDeleteResp
}
var file_user_proto_depIdxs = []int32{
	1,  // 0: proto.OrderCreateResp.data:type_name -> proto.OrderInfo
	1,  // 1: proto.OrderGetResp.data:type_name -> proto.OrderInfo
	1,  // 2: proto.OrderListResp.data:type_name -> proto.OrderInfo
	1,  // 3: proto.OrderUpdateResp.data:type_name -> proto.OrderInfo
	2,  // 4: proto.OrderService.OrderCreate:input_type -> proto.OrderCreateReq
	4,  // 5: proto.OrderService.OrderGet:input_type -> proto.OrderGetReq
	6,  // 6: proto.OrderService.OrderList:input_type -> proto.OrderListReq
	8,  // 7: proto.OrderService.OrderUpdate:input_type -> proto.OrderUpdateReq
	10, // 8: proto.OrderService.OrderDelete:input_type -> proto.OrderDeleteReq
	3,  // 9: proto.OrderService.OrderCreate:output_type -> proto.OrderCreateResp
	5,  // 10: proto.OrderService.OrderGet:output_type -> proto.OrderGetResp
	7,  // 11: proto.OrderService.OrderList:output_type -> proto.OrderListResp
	9,  // 12: proto.OrderService.OrderUpdate:output_type -> proto.OrderUpdateResp
	11, // 13: proto.OrderService.OrderDelete:output_type -> proto.OrderDeleteResp
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
